#!/usr/bin/env ruby

# This script updates the deployed CloudFront distributions based on the current local configuration.
require_relative '../../deployment'
require 'aws-sdk'
require_relative './cloudfront'

puts "Cloudfront Config: #{cloudfront_config(CDO.cloudfront[:pegasus].merge(iam_certificate_id: CDO.iam_certificate_id), CDO.http_cache[:pegasus])}"

# Default region for storing CloudFront distributions.
CF_REGION = 'us-east-1'

cloudfront = Aws::CloudFront::Client.new(
  region: CF_REGION,
  access_key_id: CDO.s3_access_key_id,
  secret_access_key: CDO.s3_secret_access_key
)
new_config = cloudfront_config(CDO.cloudfront[:pegasus], CDO.http_cache[:pegasus])
response = cloudfront.create_distribution(
  distribution_config: new_config
)
cloudfront.wait_until(:distribution_deployed, id: response.distribution.id) do |waiter|
  waiter.before_wait { |_| puts 'Waiting for distribution to deploy..' }
end
puts 'Distribution creation complete!'
