#!/usr/bin/env ruby

# This script updates the deployed CloudFront distributions based on the current local configuration.
require_relative '../../deployment'
require 'aws-sdk'
require_relative './cloudfront'

puts "Cloudfront Config: #{cloudfront_config(CDO.cloudfront[:pegasus], CDO.http_cache[:pegasus])}"

# Default region for storing CloudFront distributions.
CF_REGION = 'us-east-1'

cloudfront = Aws::CloudFront::Client.new(
  region: CF_REGION,
  access_key_id: CDO.s3_access_key_id,
  secret_access_key: CDO.s3_secret_access_key
)
distribution_id = CDO.cloudfront_pegasus_id
config = cloudfront.get_distribution_config(id: distribution_id)
puts "Config: #{config.distribution_config}"
=begin
cloudfront.update_distribution_config(
  id: distribution_id,
  if_match: config.etag,
  distribution_config: new_config
)
cloudfront.wait_until(:distribution_deployed, id: distribution_id) do |waiter|
  waiter.before_wait { |_| puts 'Waiting for distribution to deploy..' }
end
puts 'Distribution update complete!'
=end
