---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cdo-nodejs::default]
